name: my-front
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master
        
      - name: archive drcloud 
        run: tar cvfz ./drcloud.tar.gz *
      
      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./drcloud.tar.gz s3://github-action-codedeploy-s3/archive/
        
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name githubaction-test
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name githubaction-test-group
          --s3-location bucket=github-action-codedeploy-s3,bundleType=tgz,key=archive/drcloud.tar.gz
